_config:
    value:
        arch:
            args:
                batch_classifier_layers_power:
                    - 500
                    - 2000
                    - 2000
                batch_classifier_layers_weak:
                    - 128
                batch_encoder_hidden_layers:
                    - 500
                bio_encoder_hidden_layers:
                    - 500
                    - 2000
                    - 2000
                cell_classifier_layers:
                    - 64
                    - 32
                decoder_hidden_layers:
                    - 2000
                    - 2000
                    - 500
                in_sz: 40
                latent_sz: 20
                num_batch: 4
                out_sz: 40
            type: IMCVAE
        data_loader:
            args:
                batch_size: 128
                dataset: IMMUcan
                num_workers: 2
                shuffle: true
            type: IMCDataset
        lr_scheduler:
            args:
                gamma: 0.1
                step_size: 50
            type: StepLR
        n_gpu: 1
        name: IMMUcan
        optimizer:
            args:
                amsgrad: true
                weight_decay: 1e-05
            type: Adam
        param_groups:
            batch_classifier: 0.0001
            batch_encoder: 0.0001
            bio_classifier: 0.001
            bio_encoder: 0.0001
            decoder: 0.0001
        seed: 2195643142
        trainer:
            early_stop: 20
            epochs: 81
            if_imc: true
            loss_weights:
                classifier: 0.1
                discriminator: 0.03
                kl_loss_1: 2e-05
                kl_loss_2: 0.01
                kl_loss_size: 0.01
                ortho_loss: 0.001
                recon_loss: 5
            monitor: min val_loss
            save_dir: saved/
            save_period: 10
            use_vamp: false
            verbosity: 2
_log_dir:
    value: saved/log/IMMUcan/0225_155017
_save_dir:
    value: saved/models/IMMUcan/0225_155017
_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
log_levels:
    value:
        "0": 30
        "1": 20
        "2": 10
resume:
    value: null
