name: Hoch
n_gpu: 1
seed: null

arch:
  type: IMCVAE
  args:
    in_sz: 41
    bio_encoder_hidden_layers: [500, 2000, 2000]
    batch_encoder_hidden_layers: [500]
    latent_sz: 20
    decoder_hidden_layers: [2000, 2000, 500]
    out_sz: 41
    batch_classifier_layers_power: [500, 2000, 2000]
    batch_classifier_layers_weak: [128]
    num_batch: 39
    cell_classifier_layers: [64, 32]

data_loader:
  type: Hoch
  args:
    dataset: null  
    batch_size: 128
    shuffle: true
    num_workers: 2

optimizer:
  type: Adam
  args:
    weight_decay: 0.00001
    amsgrad: true
    param_groups:
      bio_encoder: 0.0001
      batch_encoder: 0.0001
      decoder: 0.0001
      mean_decoder: 0.0001
      dispersion_decoder: 0.0001
      dropout_decoder: 0.0001
      bio_classifier: 0.001
      batch_classifier: 0.0001

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 81
  save_dir: "saved/"
  save_period: 10
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 20
  use_vamp: False
  loss_weights:
    recon_loss: 5
    batch_loss_z1: 0.03
    batch_loss_z2: 0.1
    kl_loss_1: 0.00002
    kl_loss_2: 0.01
    ortho_loss: 0.001
    kl_loss_size: 0.01
